module.exports = [
    {
        "event_start_unix": 1510138800,
        "event_end_unix": 1510200000,
        "id": 53707,
        "lot_id": 745,
        "name": "Olympia",
        "city_id": 57,
        "spots": 3,
        "address": "1004 St Catherine St E",
        "zip": "H2L 2G2",
        "phone": "5142742719",
        "email": "contact@cuisinederue.org",
        "fee": 3300,
        "lat": 45.517113,
        "lng": -73.557286,
        "img":"RPNXhPfkQFOzhI8v9I6w_5900 pic.jpg",
        "event_type":0,
        "score":"0.00",
        "total_ratings":0,
        "truck_name":"Bison Burger Truck",
        "truck_id":826,
        "truck_img":"s2gtD7YSyOdOjzOHwLRI_IMG_0041.JPG",
        "tz_abb":"PST",
        "normal_pin_url":"https://lotmom.imgix.net/mLvehCaVRBGm8bDI83sO_selected-pin.png",
        "selected_pin_url":"https://lotmom.imgix.net/mLvehCaVRBGm8bDI83sO_selected-pin.png",
        "vendor_start_time":null,
        "vendor_end_time":null,
        "attending":[
            {
                "name":"PostcardsCAS",
                "email":"events@postcardsCAS.com",
                "twitter":"postcardsCAS",
                "yelp":"",
                "facebook":"postcardsCAS",
                "website":"http:\/\/www.postcardsCAS.com",
                "id":129,
                "fkey":"DRJItevmQVyG5RxDYFua_faux truck4.jpg",
                "icon":"UwyXuqoKgPQetNvUDpbkYsVEbBdOPzjZkHKtWdBcocJMYaxCRwNmOEayTSnAOamQfUCzGKuczXBnWsFlMDAA.jpg",
                "full":"flZUhrXMBshmLdyrGpepDKPLTRnlyxfunQEuwfweGITKurQITJqCMxLjMSAlYvJiLRtOxWEDdFsAmGNOicqc.jpg",
                "small":"huxAuqMfLoEHmXsrsqCgQXveLWwFlvGbaLGBQVjikwVrXJoKcIRzgEpYxmBbFCnIUfjTZWReHXIhyxbWlOyq.jpg",
                "cuisine_type":"Soul Food",
                "spot":0,
                "description":"",
                "vendor_start_time":null,
                "vendor_end_time":null,
                "vendor_start":null,
                "vendor_end":null,
                "vendor_formatted_date":null
            }
        ],
        "jquery_date": "11/08/2017",
        "g_date": "6",
        "date": "Wednesday, November 8, 2017",
        "start": "06:00 AM",
        "end": "11:00 PM",
        "formatted_date": "06:00 AM - 11:00 PM",
        "vendor_formatted_date": "07:00 PM - 07:00 PM"
    },
    {
        "event_start_unix": 1510311600,
        "event_end_unix": 1510372800,
        "id": 53709,
        "lot_id": 745,
        "name": "Place du Canada",
        "city_id": 57,
        "spots": 3,
        "address": "536 Avenue Duluth E",
        "zip": "H2L 1A9",
        "phone": "5142742719",
        "email": "contact@cuisinederue.org",
        "fee": 3300,
        "lat": 45.522195,
        "lng": -73.574452,
        "img":"XGqeyKnQ7aNygl4gTyvn_wework.jpeg",
        "event_type":0,
        "score":"0.00",
        "total_ratings":0,
        "truck_name":"Boba ni Taco",
        "truck_id":110,
        "truck_img":"2E4FdPgjTbWBOQCYWhCf_TRUCK BLUE SIDE PHOTO.jpg",
        "tz_abb":"PST",
        "normal_pin_url": "https://lotmom.imgix.net/mLvehCaVRBGm8bDI83sO_selected-pin.png",
        "selected_pin_url": "https://lotmom.imgix.net/pMUVOVs8QNGnwcreJN54_green-pin.png",
        "vendor_start_time":null,
        "vendor_end_time":null,
        "attending":[
            {
                "name":"Boba ni Taco",
                "email":"bobanitaco@gmail.com",
                "twitter":"Boba_ni_Taco",
                "yelp":"yelpcombizboba-ni-taco-diamond-bar-3",
                "facebook":"httpwwwfacebookcompagesBoba-ni-Taco119545298150647",
                "website":"http:\/\/www.bobanitaco.com",
                "id":110,
                "fkey":"2E4FdPgjTbWBOQCYWhCf_TRUCK BLUE SIDE PHOTO.jpg",
                "icon":"lrtbKQtJMGlLXPiOQCVnXFSBlJFyLmHlwnCUZqPkCYeDsYmdnKijAfhUwkEKpAhxGHdBbYOdSxNZDyQpuWhg.jpg",
                "full":"EeicPTzxYpaxoqBkmwzuWtmtucSUETqOdXydrMHVZhvboBtwPkcErsJbGqFQfmZovhlKLUHKSVnOWjPYijyD.jpg",
                "small":"bwQOXmrDSaeVmgfCQCuJgiCuqVUhNKEsvmsFPdXpsBenIKDkPOZSqZegUNgroqhLTXzahTDxSeQXINDQnkCK.jpg",
                "cuisine_type":"Asian fusion",
                "spot":0,
                "description":"",
                "vendor_start_time":null,
                "vendor_end_time":null,
                "vendor_start":null,
                "vendor_end":null,
                "vendor_formatted_date":null
            }
        ],
        "jquery_date": "11/10/2017",
        "g_date": "6",
        "date": "Friday, November 10, 2017",
        "start": "06:00 AM",
        "end": "11:00 PM",
        "formatted_date": "06:00 AM - 11:00 PM",
        "vendor_formatted_date": "11:30 AM - 02:00 PM"
    },
    {
        "event_start_unix": 1510138800,
        "event_end_unix": 1510200000,
        "id": 53707,
        "lot_id": 745,
        "name": "Place du Canada",
        "city_id": 57,
        "spots": 3,
        "address": "1225 Boul St-Laurent",
        "zip": "H2X 2S6",
        "phone": "5142742719",
        "email": "contact@cuisinederue.org",
        "fee": 3300,
        "lat": 45.509806,
        "lng": -73.563380,
        "img":"u9DSQBkSTmVzmOy3gLBz_Outside Building.jpg",
        "event_type":1,
        "score":"0.00",
        "total_ratings":0,
        "truck_name":"the deli doctor",
        "truck_id":817,
        "truck_img":"KfgCCfqcTBuqQTC81lQE_truck1.jpg",
        "tz_abb":"PST",
        "normal_pin_url": "https://lotmom.imgix.net/mLvehCaVRBGm8bDI83sO_selected-pin.png",
        "selected_pin_url": "https://lotmom.imgix.net/pMUVOVs8QNGnwcreJN54_green-pin.png",
        "vendor_start_time":null,
        "vendor_end_time":null,
        "attending":[
            {
                "name":"the deli doctor",
                "email":"thedelidoctor@gmail.com",
                "twitter":"thedelidoctor",
                "yelp":"delidoctor",
                "facebook":"thedelidoctor",
                "website":"http:\/\/delidoctor.com",
                "id":817,
                "fkey":"KfgCCfqcTBuqQTC81lQE_truck1.jpg",
                "icon":"1zYJoZDqTKeDmKoy6khP_truck1.jpg",
                "full":"C4uVzdhwSGyq6JklnZbt_truck1.jpg",
                "small":"FnVA4y27SuCcaC9OXGWl_truck1.jpg",
                "cuisine_type":"Deli",
                "spot":0,
                "description":"",
                "vendor_start_time":null,
                "vendor_end_time":null,
                "vendor_start":null,
                "vendor_end":null,
                "vendor_formatted_date":null
            }
        ],
        "jquery_date": "11/08/2017",
        "g_date": "6",
        "date": "Wednesday, November 8, 2017",
        "start": "06:00 AM",
        "end": "11:00 PM",
        "formatted_date": "06:00 AM - 11:00 PM",
        "vendor_formatted_date": "07:00 PM - 07:00 PM"
    },
    {
        "event_start_unix": 1510311600,
        "event_end_unix": 1510372800,
        "id": 53709,
        "lot_id": 745,
        "name": "Contemporary Art Museum of Montreal",
        "city_id": 57,
        "spots": 3,
        "address": "185 Saint-Catherine St W",
        "zip": "H2X 3X5",
        "phone": "5142742719",
        "email": "contact@cuisinederue.org",
        "fee": 3300,
        "lat": 45.507460,
        "lng": -73.566041,
        "img": "SXTQ1jBcTzKKA1Fanaoe_IMG_6392.JPG",
        "event_type": 0,
        "score": "0.00",
        "total_ratings": 0,
        "truck_name": "Schnitzel Truck",
        "truck_id": 1609,
        "truck_img": "MGM4kGMR5Om1dSBXtK4k_IMG_4154.jpg",
        "tz_abb": "EST",
        "normal_pin_url": "https://lotmom.imgix.net/mLvehCaVRBGm8bDI83sO_selected-pin.png",
        "selected_pin_url": "https://lotmom.imgix.net/pMUVOVs8QNGnwcreJN54_green-pin.png",
        "vendor_start_time": 1510331400,
        "vendor_end_time": 1510340400,
        "attending": [
            {
                "name": "Schnitzel Truck",
                "email": "info@dasfoodtruck.com",
                "twitter": "dasfoodtruck",
                "yelp": "dasfoodtruck",
                "facebook": "dasfoodtruck",
                "website": "http://dasfoodtruck.com",
                "id": 1609,
                "fkey": "MGM4kGMR5Om1dSBXtK4k_IMG_4154.jpg",
                "icon": "nnNcREV5RfsjmIc4U6Ug_12189972_1697482843814933_8388974026557176028_n.jpg",
                "full": "AOmvX5MaSuCmeOMNZMOt_12189972_1697482843814933_8388974026557176028_n.jpg",
                "small": "3E3JxihNRVWlbdvsKJhm_12189972_1697482843814933_8388974026557176028_n.jpg",
                "cuisine_type": "German",
                "spot": 0,
                "description": "",
                "vendor_start_time": 1510331400,
                "vendor_end_time": 1510340400,
                "vendor_start": "11:30 AM",
                "vendor_end": "02:00 PM",
                "vendor_formatted_date": "11:30 AM - 02:00 PM"
            }
        ],
        "jquery_date": "11/10/2017",
        "g_date": "6",
        "date": "Friday, November 10, 2017",
        "start": "06:00 AM",
        "end": "11:00 PM",
        "formatted_date": "06:00 AM - 11:00 PM",
        "vendor_formatted_date": "11:30 AM - 02:00 PM"
    },
    {
        "event_start_unix": 1510138800,
        "event_end_unix": 1510200000,
        "id": 53707,
        "lot_id": 745,
        "name": "Place du Canada",
        "city_id": 57,
        "spots": 3,
        "address": "57 Rue Prince Arthur E",
        "zip": "H2X 1B4",
        "phone": "5142742719",
        "email": "contact@cuisinederue.org",
        "fee": 3300,
        "lat": 45.514647,
        "lng": -73.572221,
        "img":"5To2b3LqTxOOilJbPw6V_200-300-CP-aerial.jpg",
        "event_type":0,
        "score":"0.00",
        "total_ratings":0,
        "truck_name":"Swamis Sandwiches",
        "truck_id":872,
        "truck_img":"WxRzvVdQJuyJLQENgpNO_Swami's Truck.JPG",
        "tz_abb":"PST",
        "normal_pin_url": "https://lotmom.imgix.net/mLvehCaVRBGm8bDI83sO_selected-pin.png",
        "selected_pin_url": "https://lotmom.imgix.net/pMUVOVs8QNGnwcreJN54_green-pin.png",
        "vendor_start_time":null,
        "vendor_end_time":null,
        "attending":[
            {
                "name":"Swamis Sandwiches",
                "email":"ram@swamissandwiches.com",
                "twitter":"sandwichswami",
                "yelp":"swamis-sandwiches-food-truck-los-angeles",
                "facebook":"swamissandwiches",
                "website":"http:\/\/www.swamissandwiches.com",
                "id":872,
                "fkey":"WxRzvVdQJuyJLQENgpNO_Swami's Truck.JPG",
                "icon":"759mA8wxSre4Nykzi2z3_IMG_6709.JPG",
                "full":"xXnRFC4dRZ6D4NOTSEaZ_IMG_6709.JPG",
                "small":"azWsewvPQkIVhZwVq6lA_IMG_6709.JPG",
                "cuisine_type":"Deli",
                "spot":0,
                "description":"",
                "vendor_start_time":null,
                "vendor_end_time":null,
                "vendor_start":null,
                "vendor_end":null,
                "vendor_formatted_date":null
            }
        ],
        "jquery_date": "11/08/2017",
        "g_date": "6",
        "date": "Wednesday, November 8, 2017",
        "start": "06:00 AM",
        "end": "11:00 PM",
        "formatted_date": "06:00 AM - 11:00 PM",
        "vendor_formatted_date": "07:00 PM - 07:00 PM"
    },
    {
        "event_start_unix": 1510311600,
        "event_end_unix": 1510372800,
        "id": 53709,
        "lot_id": 745,
        "name": "MTELUS",
        "city_id": 57,
        "spots": 3,
        "address": "59 St Catherine St E",
        "zip": "H2X 1K5",
        "phone": "5142742719",
        "email": "contact@cuisinederue.org",
        "fee": 3300,
        "lat": 45.510648,
        "lng": -73.563466,
        "img":"evfkgqA6TzO1gloZw41V_REEF_bldgimage copy.jpg",
        "event_type":0,
        "score":"0.88",
        "total_ratings":17,
        "truck_name":"MAC'D N LOADED",
        "truck_id":1956,
        "truck_img":"kZE7NvC5TPGCyUCJMOvD_truck%20pic.JPG",
        "tz_abb":"PST",
        "normal_pin_url": "https://lotmom.imgix.net/mLvehCaVRBGm8bDI83sO_selected-pin.png",
        "selected_pin_url": "https://lotmom.imgix.net/pMUVOVs8QNGnwcreJN54_green-pin.png",
        "vendor_start_time":null,
        "vendor_end_time":null,
        "attending":[
            {
                "name":"MAC'D N LOADED",
                "email":"macdnloaded@gmail.com",
                "twitter":"",
                "yelp":"",
                "facebook":"",
                "website":"",
                "id":1956,
                "fkey":"kZE7NvC5TPGCyUCJMOvD_truck pic.JPG",
                "icon":"rPTadT2RRHiaGieQU9e6_truck pic.JPG",
                "full":"dHUIAg8ES2CJdTUHzATM_truck pic.JPG",
                "small":"YeBXOkt9R2OWP1O6KQ4r_truck pic.JPG",
                "cuisine_type":"American Comfort",
                "spot":0,
                "description":"",
                "vendor_start_time":null,
                "vendor_end_time":null,
                "vendor_start":null,
                "vendor_end":null,
                "vendor_formatted_date":null
            }
        ],
        "jquery_date": "11/10/2017",
        "g_date": "6",
        "date": "Friday, November 10, 2017",
        "start": "06:00 AM",
        "end": "11:00 PM",
        "formatted_date": "06:00 AM - 11:00 PM",
        "vendor_formatted_date": "11:30 AM - 02:00 PM"
    },
    {
        "event_start_unix": 1510138800,
        "event_end_unix": 1510200000,
        "id": 53707,
        "lot_id": 745,
        "name": "UQAM",
        "city_id": 57,
        "spots": 3,
        "address": "2098 Rue Kimberley",
        "zip": "H2X",
        "phone": "5142742719",
        "email": "contact@cuisinederue.org",
        "fee": 3300,
        "lat": 45.509565,
        "lng": -73.569131,
        "img":"PaWqKv6oQ3W24nmgNws7_mw.jpg",
        "event_type":0,
        "score":"0.00",
        "total_ratings":0,
        "truck_name":"MiddleFeast",
        "truck_id":678,
        "truck_img":"ydCoTwndTyyBwQnuzP5N_XT0500_Middle-Feast-01_s4x3.jpg.rend.snigalleryslide.jpeg",
        "tz_abb":"PST",
        "normal_pin_url": "https://lotmom.imgix.net/mLvehCaVRBGm8bDI83sO_selected-pin.png",
        "selected_pin_url": "https://lotmom.imgix.net/pMUVOVs8QNGnwcreJN54_green-pin.png",
        "vendor_start_time":null,
        "vendor_end_time":null,
        "attending":[
            {
                "name":"MiddleFeast",
                "email":"info@middlefeastfoodtruck.com",
                "twitter":"MidFeastTruck",
                "yelp":"the-middle-feast-food-truck-los-angeles",
                "facebook":"pagesThe-Middle-Feast-Food-Truck369479796523592refbookmarks",
                "website":"http:\/\/middlefeastfoodtruck.com",
                "id":678,
                "fkey":"ydCoTwndTyyBwQnuzP5N_XT0500_Middle-Feast-01_s4x3.jpg.rend.snigalleryslide.jpeg",
                "icon":"kemuUDBHJVcLTCIAEFLJQSgIshdiVGtgBzvgPbaYWFSUtFrmRZXuPfvKQuBZtCGTGyljcZdAZwtfXfkkOEvH.jpeg",
                "full":"uuwcsyUvQrHEtOcoVBjLxdbfkzjYrMKdMIRqofZhANqhJwgDOMWSFuwkAgMSefVINORYCtvsEUqRPTNWGaOL.jpeg",
                "small":"yjicBGJKZnnQazzwMNIQvuVeBRwFCyKJJSMTwNMigOkoKjbhnSYofZkCQNLFyxWOqEXubKWTiDjwskPPfGxe.jpeg",
                "cuisine_type":"Mediteranean",
                "spot":0,
                "description":"",
                "vendor_start_time":null,
                "vendor_end_time":null,
                "vendor_start":null,
                "vendor_end":null,
                "vendor_formatted_date":null
            }
        ],
        "jquery_date": "11/08/2017",
        "g_date": "6",
        "date": "Wednesday, November 8, 2017",
        "start": "06:00 AM",
        "end": "11:00 PM",
        "formatted_date": "06:00 AM - 11:00 PM",
        "vendor_formatted_date": "07:00 PM - 07:00 PM"
    },
    {
        "event_start_unix": 1510138800,
        "event_end_unix": 1510200000,
        "id": 53707,
        "lot_id": 745,
        "name": "McCord Museum",
        "city_id": 57,
        "spots": 3,
        "address": "690 Sherbrooke St W",
        "zip": "H3A 1E9",
        "phone": "5142742719",
        "email": "contact@cuisinederue.org",
        "fee": 3300,
        "lat": 45.504362,
        "lng": -73.573594,
        "img":"wfNZcDNoQ1OWgL0Zt5Q2_image.jpg",
        "event_type":0,
        "score":"0.00",
        "total_ratings":0,
        "truck_name":"Oaxaca on Wheels ",
        "truck_id":888,
        "truck_img":"PUwXmpztRccJ9WFBZdrk_image.jpg",
        "tz_abb":"PST",
        "normal_pin_url": "https://lotmom.imgix.net/mLvehCaVRBGm8bDI83sO_selected-pin.png",
        "selected_pin_url": "https://lotmom.imgix.net/pMUVOVs8QNGnwcreJN54_green-pin.png",
        "vendor_start_time":null,
        "vendor_end_time":null,
        "attending":[
            {
                "name":"Oaxaca on Wheels ",
                "email":"Oaxacaonwheels@gmail.com",
                "twitter":"oaxacaonwheels",
                "yelp":"",
                "facebook":"Oaxacaonwheels",
                "website":"http:\/\/www.oaxacaonwheels.com",
                "id":888,
                "fkey":"PUwXmpztRccJ9WFBZdrk_image.jpg",
                "icon":"ZGyjmjj3SLKmLbrVIFxY_image.jpg",
                "full":"Mrl3LcLiS8ikzy0dEubp_image.jpg",
                "small":"UP02wA8fS6u4UiFZ5nyS_image.jpg",
                "cuisine_type":"Mexican",
                "spot":0,
                "description":"",
                "vendor_start_time":null,
                "vendor_end_time":null,
                "vendor_start":null,
                "vendor_end":null,
                "vendor_formatted_date":null
            }
        ],
        "jquery_date": "11/08/2017",
        "g_date": "6",
        "date": "Wednesday, November 8, 2017",
        "start": "06:00 AM",
        "end": "11:00 PM",
        "formatted_date": "06:00 AM - 11:00 PM",
        "vendor_formatted_date": "07:00 PM - 07:00 PM"
    },
    {
        "event_start_unix": 1510311600,
        "event_end_unix": 1510372800,
        "id": 53709,
        "lot_id": 745,
        "name": "Schwartz's Deli",
        "city_id": 57,
        "spots": 3,
        "address": "3895 St Laurent Blvd",
        "zip": "H2W 1X9",
        "phone": "5142742719",
        "email": "contact@cuisinederue.org",
        "fee": 3300,
        "lat": 45.516361,
        "lng": -73.577671,
        "img":"TV1uLaARTBVyc8BcTTnc_carefirstlot.jpg",
        "event_type":0,
        "score":"0.00",
        "total_ratings":0,
        "truck_name":"The Tackle Box",
        "truck_id":959,
        "truck_img":"j2CZtI7NQsu6dDWSkjVX_image.jpg",
        "tz_abb":"PST",
        "normal_pin_url": "https://lotmom.imgix.net/mLvehCaVRBGm8bDI83sO_selected-pin.png",
        "selected_pin_url": "https://lotmom.imgix.net/pMUVOVs8QNGnwcreJN54_green-pin.png",
        "vendor_start_time":null,
        "vendor_end_time":null,
        "attending":[
            {
                "name":"The Tackle Box",
                "email":"Thetackleboxsocal@gmail.com",
                "twitter":"TheTackleBox_SC",
                "yelp":"",
                "facebook":"TheTackleBoxFoodTruck",
                "website":"",
                "id":959,
                "fkey":"j2CZtI7NQsu6dDWSkjVX_image.jpg",
                "icon":"kp10Ug9SVKASSCI5mqYD_Truck Pic 3.jpg",
                "full":"qMYH9xvjRYq7uqLtnU4V_Truck Pic 3.jpg",
                "small":"OoPk5QrFRFi7HNpPaWgU_Truck Pic 3.jpg",
                "cuisine_type":"Gourmet Seafood",
                "spot":1,
                "description":"",
                "vendor_start_time":null,
                "vendor_end_time":null,
                "vendor_start":null,
                "vendor_end":null,
                "vendor_formatted_date":null
            }
        ],
        "jquery_date": "11/10/2017",
        "g_date": "6",
        "date": "Friday, November 10, 2017",
        "start": "06:00 AM",
        "end": "11:00 PM",
        "formatted_date": "06:00 AM - 11:00 PM",
        "vendor_formatted_date": "11:30 AM - 02:00 PM"
    }
]